# This is a basic workflow to help you get started with Actions

name: Build & Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
     - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v -o gauk.as ./src

    - name: Test
      run: go test -v ./src

  deploy:
    if: ${{ github.ref == 'main' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
          
    - name: Auto pull & rebuilt
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_TO }}
        username: gaukas
        key: ${{ secrets.DEPLOYER_PRIVKEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        script: |
          cd ~/sites/gauk_as/Gauk.as && make
